name: Run Node.js Script

on:
  schedule:
    - cron: '0 12 * * *'  # 毎分に実行（UTC時間）
  workflow_dispatch:  # 手動トリガーを有効にする

jobs:
  run-script:
    runs-on: windows-latest  # Windows環境で実行
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # 最新のバージョンに更新

      - name: Set up Node.js
        uses: actions/setup-node@v3  # 最新のバージョンに更新
        with:
          node-version: '20'  # 使用するNode.jsのバージョン

      - name: Install dependencies
        run: |
          if (Test-Path package.json) {
            npm install || { Write-Host "npm install failed"; exit 1; }
          } else {
            Write-Host "No package.json found, skipping npm install."
          }

      - name: Run script
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}  # SlackのWebhook URLを環境変数として設定
        run: |
          if (Test-Path script.js) {
            node script.js || { Write-Host "script.js execution failed"; exit 1; }
          } else {
            Write-Host "script.js not found, skipping script execution."
          }

      - name: Send success message to Slack
        if: success()  # スクリプトが成功した場合のみ実行
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Script executed successfully!"}' "${{ secrets.SLACK_WEBHOOK_URL }}"
      - name: Send failure message to Slack
        if: failure()  # スクリプトが失敗した場合のみ実行
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Script execution failed!"}'"${{ secrets.SLACK_WEBHOOK_URL }}"
