name: Run Node.js Script

on:
  schedule:
    - cron: '* * * * *'  # 毎分に実行（UTC時間）
  workflow_dispatch:  # 手動トリガーを有効にする

jobs:
  run-script:
    runs-on: windows-latest  # Windows環境で実行
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # 使用するNode.jsのバージョン

      - name: Install dependencies
        run: |
          if (Test-Path package.json) {
            npm install
          } else {
            Write-Host "No package.json found, skipping npm install."
          }

      - name: Run script
        run: node script.js  # script.jsを実行
